{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wassersport.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wassersport.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "wassersport.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
